apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb-deployment-volume-mount-demo
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
          - name:  MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mysql-cred
                key:  MYSQL_ROOT_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts: #mentioning volume mount for calling .conf file
          - name:  newcm
            mountPath:  /etc/mysql/conf.d
            readOnly: true
      volumes:
        - name:  newcm
          configMap: 
            name: mysql-extra    
